
#---------- 单注册中心配置 ------------
#server:
#  port: 8761
#eureka:
#  client:
#    #是否将自己注册到eureka server
#    registerWithEureka: false
#    #是否从eureka server获取注册信息，默认为true，因为这是一个单点的eureka server,不需要同步其他eureka server数据节点，故而设置为false
#    fetchRegistry: false
#    serviceUrl:
#      #设置eureka server交互地址，多个可以用逗号分隔
#      defaultZone: http://localhost:8761/eureka/



#------------ 高可用配置 --------
spring:
  application:
    name: microservice-discovery-eureka-ha
# "---" 代表了连字符
---
spring:
  #指定profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    #当指定profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    serviceUrl:
      #将自己注册到peer2这个服务中心上去
      defaultZone: http://peer2:8762/eureka/
---
spring:
  #指定profile=peer2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    #当指定profile=peer2时，主机名是peer2
    hostname: peer2
  client:
    serviceUrl:
      #将自己注册到peer1这个服务中心上去
      defaultZone: http://peer1:8761/eureka/